<?php
/**
 * WP-S02 step 1: save a V4 atomic block as a TEMPLATE via the REAL
 * Source_Local::save_item() path (== what POST /wp-json/elementor/v1/template-library/templates
 * -> Endpoints\Templates::create_items() invokes).
 *
 * - Ensures global class "s02card" exists in the kit (repo diff API).
 * - Builds an atomic block: e-div-block(.s02card) > (e-heading[local#1] + e-button[local#2]).
 * - Saves via templates_manager->get_source('local')->save_item([...,'type'=>'container',...]).
 * - Captures the stored template _elementor_data and proves:
 *     * element ids were re-generated by replace_elements_ids (NOT == source ids)
 *     * local style maps survived + their ids still match settings.classes.value
 *     * the global-class reference (s02card) survived in settings.classes.value
 *     * what relations meta the saved TEMPLATE carries
 * - Also calls get_data() (the editor insert/read side) to capture the
 *   `global_classes` snapshot that the import/merge step consumes.
 *
 * Writes /spikes/s02-state.json for the import step.
 */

use Elementor\Plugin;
use Elementor\Modules\GlobalClasses\Global_Classes_Repository;

if ( ! defined( 'ABSPATH' ) ) { exit; }

$admin = get_user_by( 'login', 'admin' );
if ( $admin ) { wp_set_current_user( $admin->ID ); }

function s02_out( $label, $val ) {
	echo "==== $label ====\n";
	echo ( is_string( $val ) ? $val : print_r( $val, true ) ) . "\n";
}

$mod = Plugin::$instance->experiments;
s02_out( 'EXPERIMENTS', [
	'e_atomic_elements' => $mod->is_feature_active( 'e_atomic_elements' ),
	'e_classes'         => $mod->is_feature_active( 'e_classes' ),
	'e_variables'       => $mod->is_feature_active( 'e_variables' ),
] );

// ---------------------------------------------------------------------------
// 1) Ensure global class s02card exists in the kit.
// ---------------------------------------------------------------------------
$gc_id = 's02card';
$repo = Global_Classes_Repository::make()->set_preview( false );
$existing = $repo->all()->get_items()->all();
$existing_order = $repo->get_order();

$gc_item = [
	'id' => $gc_id, 'type' => 'class', 'label' => $gc_id,
	'variants' => [ [
		'meta' => [ 'breakpoint' => 'desktop', 'state' => null ],
		'props' => [
			'background' => [ '$$type' => 'background', 'value' => [ 'color' => [ '$$type' => 'color', 'value' => 'rgb(12, 34, 56)' ] ] ],
			'padding' => [ '$$type' => 'dimensions', 'value' => [
				'block-start' => [ '$$type' => 'size', 'value' => [ 'unit' => 'px', 'size' => 20 ] ],
				'block-end'   => [ '$$type' => 'size', 'value' => [ 'unit' => 'px', 'size' => 20 ] ],
				'inline-start'=> [ '$$type' => 'size', 'value' => [ 'unit' => 'px', 'size' => 28 ] ],
				'inline-end'  => [ '$$type' => 'size', 'value' => [ 'unit' => 'px', 'size' => 28 ] ],
			] ],
		],
	] ],
];
$touched = [ $gc_id => $gc_item ];
$changes = [
	'added'    => isset( $existing[ $gc_id ] ) ? [] : [ $gc_id ],
	'deleted'  => [],
	'modified' => isset( $existing[ $gc_id ] ) ? [ $gc_id ] : [],
	'order'    => false,
];
$order = $existing_order;
if ( ! in_array( $gc_id, $order, true ) ) { $order[] = $gc_id; }
try {
	$repo->apply_changes( $touched, $changes, $order );
	s02_out( 'GLOBAL_CLASS_APPLY', 'OK ' . $gc_id );
} catch ( \Throwable $e ) {
	s02_out( 'GLOBAL_CLASS_APPLY_ERROR', $e->getMessage() );
}
$kit_order_before = Global_Classes_Repository::make()->set_preview( false )->get_order();
s02_out( 'KIT_GLOBAL_CLASS_ORDER_BEFORE_SAVE', $kit_order_before );

// ---------------------------------------------------------------------------
// 2) Build the atomic block tree (source ids are deterministic so we can
//    prove they get remapped on save).
// ---------------------------------------------------------------------------
$src_div  = 's02div01';
$src_head = 's02head1';
$src_btn  = 's02btn01';
$head_local = 'e-s02head1-local';
$btn_local  = 'e-s02btn01-local';

$tree = [ [
	'id' => $src_div, 'elType' => 'e-div-block', 'isInner' => false,
	'settings' => [ 'classes' => [ '$$type' => 'classes', 'value' => [ $gc_id ] ] ],
	'styles' => [],
	'elements' => [
		[
			'id' => $src_head, 'elType' => 'widget', 'widgetType' => 'e-heading', 'isInner' => false,
			'settings' => [
				'classes' => [ '$$type' => 'classes', 'value' => [ $head_local ] ],
				'tag' => [ '$$type' => 'string', 'value' => 'h2' ],
				'title' => [ '$$type' => 'html-v3', 'value' => [ 'content' => [ '$$type' => 'string', 'value' => 'S02 Atomic Card' ], 'children' => [] ] ],
			],
			'styles' => [ $head_local => [
				'id' => $head_local, 'type' => 'class', 'label' => 'headlocal',
				'variants' => [ [ 'meta' => [ 'breakpoint' => 'desktop', 'state' => null ], 'props' => [
					'color' => [ '$$type' => 'color', 'value' => 'rgb(255, 200, 0)' ],
					'font-size' => [ '$$type' => 'size', 'value' => [ 'unit' => 'px', 'size' => 36 ] ],
				] ] ],
			] ],
			'elements' => [],
		],
		[
			'id' => $src_btn, 'elType' => 'widget', 'widgetType' => 'e-button', 'isInner' => false,
			'settings' => [
				'classes' => [ '$$type' => 'classes', 'value' => [ $btn_local ] ],
				'text' => [ '$$type' => 'html-v3', 'value' => [ 'content' => [ '$$type' => 'string', 'value' => 'S02 Button' ], 'children' => [] ] ],
			],
			'styles' => [ $btn_local => [
				'id' => $btn_local, 'type' => 'class', 'label' => 'btnlocal',
				'variants' => [ [ 'meta' => [ 'breakpoint' => 'desktop', 'state' => null ], 'props' => [
					'color' => [ '$$type' => 'color', 'value' => 'rgb(0, 0, 0)' ],
					'background' => [ '$$type' => 'background', 'value' => [ 'color' => [ '$$type' => 'color', 'value' => 'rgb(0, 220, 130)' ] ] ],
				] ] ],
			] ],
			'elements' => [],
		],
	],
] ];

// ---------------------------------------------------------------------------
// 3) Save as a TEMPLATE via the real save_item path.
//    Use type 'container' (a show_in_library V4-capable doc type). Fall back
//    list printed so we can pick a valid type if needed.
// ---------------------------------------------------------------------------
$doc_types = Plugin::$instance->documents->get_document_types( [ 'show_in_library' => true ] );
s02_out( 'SHOW_IN_LIBRARY_DOC_TYPES', array_keys( $doc_types ) );

$source = Plugin::$instance->templates_manager->get_source( 'local' );
s02_out( 'SOURCE_CLASS', get_class( $source ) );

$save_type = in_array( 'container', array_keys( $doc_types ), true ) ? 'container'
	: ( in_array( 'page', array_keys( $doc_types ), true ) ? 'page' : array_keys( $doc_types )[0] );
s02_out( 'CHOSEN_TEMPLATE_TYPE', $save_type );

$result = $source->save_item( [
	'title'   => 'S02 Atomic Block Template',
	'type'    => $save_type,
	'content' => $tree,
	'page_settings' => [],
] );

if ( is_wp_error( $result ) ) {
	s02_out( 'SAVE_ITEM_WP_ERROR', $result->get_error_code() . ': ' . $result->get_error_message() );
	return;
}
$template_id = (int) $result;
s02_out( 'SAVE_ITEM_TEMPLATE_ID', $template_id );

// ---------------------------------------------------------------------------
// 4) Inspect the stored template _elementor_data.
// ---------------------------------------------------------------------------
$raw = get_post_meta( $template_id, '_elementor_data', true );
s02_out( 'TEMPLATE_DATA_LEN', is_string( $raw ) ? strlen( $raw ) : '(' . gettype( $raw ) . ')' );

$stored = json_decode( $raw, true );
file_put_contents( '/spikes/s02-template-data.json', wp_json_encode( $stored, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );

// Walk to collect the stored element ids + style maps + class refs.
$stored_ids = [];
$stored_style_ids = [];
$stored_class_refs = [];
$walk = function ( $els ) use ( &$walk, &$stored_ids, &$stored_style_ids, &$stored_class_refs ) {
	foreach ( $els as $el ) {
		if ( isset( $el['id'] ) ) { $stored_ids[] = $el['id']; }
		if ( ! empty( $el['styles'] ) && is_array( $el['styles'] ) ) {
			foreach ( $el['styles'] as $sk => $sv ) { $stored_style_ids[] = $sk; }
		}
		$cv = $el['settings']['classes']['value'] ?? null;
		if ( is_array( $cv ) ) { foreach ( $cv as $c ) { $stored_class_refs[] = $c; } }
		if ( ! empty( $el['elements'] ) ) { $walk( $el['elements'] ); }
	}
};
if ( is_array( $stored ) ) { $walk( $stored ); }

s02_out( 'SOURCE_ELEMENT_IDS', [ $src_div, $src_head, $src_btn ] );
s02_out( 'STORED_ELEMENT_IDS', $stored_ids );
s02_out( 'ELEMENT_IDS_REMAPPED (source ids absent)', [
	'div_remapped'  => ! in_array( $src_div, $stored_ids, true ),
	'head_remapped' => ! in_array( $src_head, $stored_ids, true ),
	'btn_remapped'  => ! in_array( $src_btn, $stored_ids, true ),
] );
s02_out( 'STORED_STYLE_IDS', $stored_style_ids );
s02_out( 'STORED_CLASS_REFS', $stored_class_refs );

// Cross-check: in stored data, each local style id must still be present in the
// same element's settings.classes.value (the local-style <-> classes mirror).
$mirror_ok = true; $mirror_detail = [];
$walk2 = function ( $els ) use ( &$walk2, &$mirror_ok, &$mirror_detail ) {
	foreach ( $els as $el ) {
		$style_keys = array_keys( $el['styles'] ?? [] );
		$class_vals = $el['settings']['classes']['value'] ?? [];
		foreach ( $style_keys as $sk ) {
			$present = in_array( $sk, (array) $class_vals, true );
			$mirror_detail[] = $el['id'] . ' style ' . $sk . ' in classes=' . ( $present ? 'YES' : 'NO' );
			if ( ! $present ) { $mirror_ok = false; }
		}
		if ( ! empty( $el['elements'] ) ) { $walk2( $el['elements'] ); }
	}
};
if ( is_array( $stored ) ) { $walk2( $stored ); }
s02_out( 'LOCAL_STYLE_MIRROR_OK', $mirror_ok ? 'YES' : 'NO' );
s02_out( 'LOCAL_STYLE_MIRROR_DETAIL', $mirror_detail );

s02_out( 'GLOBAL_CLASS_REF_PRESENT (s02card in stored class refs)', in_array( $gc_id, $stored_class_refs, true ) ? 'YES' : 'NO' );

// Relations meta on the saved template (does save_item register relations like editor save?)
s02_out( 'TEMPLATE_RELATIONS_used_global_class(frontend)', get_post_meta( $template_id, '_elementor_used_global_class', false ) );
s02_out( 'TEMPLATE_RELATIONS_used_global_class(preview)', get_post_meta( $template_id, '_elementor_used_global_class_preview', false ) );

// ---------------------------------------------------------------------------
// 5) get_data() — the editor read/insert side. Captures the global_classes
//    snapshot the import/merge step consumes, and shows it re-IDs elements again.
// ---------------------------------------------------------------------------
$get_data = $source->get_data( [ 'template_id' => $template_id, 'with_page_settings' => true ] );
file_put_contents( '/spikes/s02-get-data.json', wp_json_encode( $get_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
s02_out( 'GET_DATA_TOP_KEYS', array_keys( $get_data ) );
s02_out( 'GET_DATA_HAS_global_classes_SNAPSHOT', isset( $get_data['global_classes'] ) ? 'YES' : 'NO' );
if ( isset( $get_data['global_classes'] ) ) {
	s02_out( 'GET_DATA_global_classes_KEYS', array_keys( $get_data['global_classes'] ) );
	$gc_items = $get_data['global_classes']['items'] ?? ( $get_data['global_classes']['data']['items'] ?? null );
	s02_out( 'GET_DATA_global_classes_ITEM_IDS', is_array( $gc_items ) ? array_keys( $gc_items ) : '(shape: ' . wp_json_encode( $get_data['global_classes'] ) . ')' );
}

// state for import step
$state = [
	'template_id'   => $template_id,
	'template_type' => $save_type,
	'gc_id'         => $gc_id,
	'head_local'    => $head_local,
	'btn_local'     => $btn_local,
	'source_ids'    => [ $src_div, $src_head, $src_btn ],
	'stored_ids'    => $stored_ids,
];
file_put_contents( '/spikes/s02-state.json', wp_json_encode( $state, JSON_PRETTY_PRINT ) );
s02_out( 'STATE_WRITTEN', $state );
