import { spawn } from 'node:child_process';
const env={...process.env,WP_URL:'http://localhost:8899',WP_USER:'admin',WP_APP_PASSWORD:'SET-VIA-WP_APP_PASSWORD-ENV',ULTRA_TOOLS:'full'};
const SZ=(n,u)=>({$$type:'size',value:{unit:u,size:n}});
const CLS=a=>({$$type:'classes',value:a});
const child=(i,w)=>({id:'c'+i,elType:'e-div-block',version:'0.0',settings:{tag:{$$type:'string',value:'div'},classes:CLS(['e-c'+i+'-s'])},styles:{['e-c'+i+'-s']:{id:'e-c'+i+'-s',type:'class',label:'c'+i+'cls',variants:[{meta:{breakpoint:'desktop',state:null},props:{width:SZ(w,'%'),'min-height':SZ(40,'px')}}]}},editor_settings:[],interactions:[],elements:[]});
const rowTree=(rid,w)=>[{id:rid,elType:'e-flexbox',version:'0.0',settings:{tag:{$$type:'string',value:'div'},classes:CLS(['e-'+rid+'-s'])},styles:{['e-'+rid+'-s']:{id:'e-'+rid+'-s',type:'class',label:rid+'cls',variants:[{meta:{breakpoint:'desktop',state:null},props:{display:{$$type:'string',value:'flex'},'flex-direction':{$$type:'string',value:'row'},gap:SZ(24,'px')}}]}},editor_settings:[],interactions:[],elements:[child(rid+'1',w),child(rid+'2',w),child(rid+'3',w),child(rid+'4',w)]}];
function dry(elements){return new Promise(res=>{const p=spawn('node',['dist/index.js'],{env,stdio:['pipe','pipe','pipe']});let buf='';p.stdout.on('data',d=>buf+=d);const send=o=>p.stdin.write(JSON.stringify(o)+'\n');send({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2024-11-05',capabilities:{},clientInfo:{name:'c',version:'1'}}});send({jsonrpc:'2.0',method:'notifications/initialized'});send({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'elementor.page.dry_run',arguments:{elements}}});setTimeout(()=>{const L=buf.split('\n').filter(Boolean).map(l=>{try{return JSON.parse(l)}catch{return null}}).filter(Boolean);const sc=L.find(l=>l.id===2)?.result?.structuredContent||{};const lay=(sc.errors||[]).find(e=>/Flex-row/.test(e.message||''));res({valid:sc.valid,lay:lay?lay.message.slice(0,140):null});p.kill();},9000);});}
console.log('25%x4+gap:',JSON.stringify(await dry(rowTree('w25',25))));
console.log('22%x4+gap:',JSON.stringify(await dry(rowTree('w22',22))));
