/**
 * WP-F02 — REST contract public barrel (Seam B).
 *
 * Re-exports the envelope types, cross-cutting field types + per-route request/response types, and the
 * route registry. The shared package root entry (`src/index.ts`, owned by WP-F01) re-exports from here
 * so consumers can `import { ... } from '@elementor-ultra/shared'`.
 *
 * Contract authority: spec/contracts/10-rest-api.md, spec/contracts/openapi.yaml,
 * spec/contracts/12-error-taxonomy.md §2.
 */

/* Envelopes (runtime guards + types). */
export {
  isRestSuccess,
  isRestError,
  type RestSuccess,
  type RestError,
  type RestErrorData,
  type RestFieldError,
  type RestResponse,
} from './envelopes.js';

/* Cross-cutting field helpers (runtime). */
export {
  OP_ID_PATTERN,
  BASE_HASH_PATTERN,
  isOpId,
  asOpId,
  isBaseHash,
  asBaseHash,
} from './types.js';

/* Cross-cutting field types + all 74 per-route request/response types. */
export type {
  /* cross-cutting */
  OpId,
  BaseHash,
  Pagination,
  Paginated,
  ElementNode,
  Generation,
  ConditionTuple,
  WatermarkToken,
  RestDiff,
  RestValidationError,
  /* documents */
  DocumentListItem,
  ListDocumentsRequest,
  ListDocumentsResponse,
  CreateDocumentRequest,
  CreateDocumentResponse,
  GetDocumentRequest,
  GetDocumentResponse,
  GetDocumentSettingsResponse,
  UpdateDocumentSettingsRequest,
  UpdateDocumentSettingsResponse,
  DryRunRequest,
  DryRunResponse,
  SaveDocumentRequest,
  SaveDocumentResponse,
  SaveWarning,
  RenderProbeResult,
  VerifyRenderResponse,
  ReplaceTreeRequest,
  ReplaceTreeResponse,
  BackupHandle,
  ElementOp,
  ElementOpsRequest,
  ElementOpsResponse,
  PrimeCssRequest,
  PrimeCssResponse,
  BackupDocumentRequest,
  BackupDocumentResponse,
  BackupListItem,
  ListBackupsRequest,
  ListBackupsResponse,
  RollbackDocumentRequest,
  RollbackDocumentResponse,
  DuplicateDocumentRequest,
  DuplicateDocumentResponse,
  DeleteDocumentRequest,
  DeleteDocumentResponse,
  ExportDocumentRequest,
  ExportDocumentResponse,
  LockStatusResponse,
  /* ids */
  DocumentIdsResponse,
  ValidateIdsRequest,
  ValidateIdsResponse,
  RemapIdsRequest,
  RemapIdsResponse,
  /* schema */
  SchemaWidgetResponse,
  SchemaStylesResponse,
  SchemaRegisteredTypesResponse,
  Breakpoint,
  SchemaBreakpointsResponse,
  /* design */
  ClassVariant,
  GlobalClass,
  ListGlobalClassesRequest,
  ListGlobalClassesResponse,
  GlobalClassesChanges,
  PutGlobalClassesRequest,
  PutGlobalClassesResponse,
  GlobalClassesUsageRequest,
  ClassUsage,
  GlobalClassesUsageResponse,
  DesignVariable,
  ListVariablesResponse,
  CreateVariableRequest,
  CreateVariableResponse,
  UpdateVariableRequest,
  UpdateVariableResponse,
  DeleteVariableResponse,
  RestoreVariableRequest,
  RestoreVariableResponse,
  VariableBatchOp,
  BatchVariablesRequest,
  BatchVariablesResponse,
  KitColor,
  GetGlobalColorsResponse,
  PutGlobalColorsRequest,
  PutGlobalColorsResponse,
  KitFont,
  GetGlobalFontsResponse,
  PutGlobalFontsRequest,
  PutGlobalFontsResponse,
  ListInstalledFontsResponse,
  InstallFontRequest,
  InstallFontResponse,
  UploadFontZipRequest,
  UploadFontZipInstalledFace,
  UploadFontZipResponse,
  GetElementDefaultsResponse,
  PutElementDefaultsRequest,
  PutElementDefaultsResponse,
  SyncV4ToV3Request,
  SyncV4ToV3Response,
  DeployClassesBlock,
  DeployVariablesBlock,
  DeployDesignRequest,
  DeployDesignResponse,
  /* media */
  MediaItem,
  ListMediaRequest,
  ListMediaResponse,
  SideloadMediaRequest,
  SideloadMediaResponse,
  UploadMediaRequest,
  UploadMediaResponse,
  /* nav */
  NavMenuItem,
  ListNavMenusResponse,
  NavMenuItemInput,
  CreateNavMenuRequest,
  CreateNavMenuResponse,
  BindNavWidgetRequest,
  BindNavWidgetResponse,
  /* templates / kits */
  TemplateListItem,
  ListTemplatesRequest,
  ListTemplatesResponse,
  GetTemplateResponse,
  SaveTemplateRequest,
  SaveTemplateResponse,
  ImportTemplateRequest,
  ImportTemplateResponse,
  InsertTemplateRequest,
  InsertTemplateResponse,
  KitExportRequest,
  KitExportResponse,
  KitImportRequest,
  KitImportResponse,
  KitRevertRequest,
  KitRevertResponse,
  /* pro */
  CreateThemeDocRequest,
  CreateThemeDocResponse,
  ThemeConditionConflict,
  SetThemeConditionsRequest,
  SetThemeConditionsResponse,
  ConditionsConfigResponse,
  CreatePopupRequest,
  CreatePopupResponse,
  SetPopupDisplayRequest,
  SetPopupDisplayResponse,
  FormFieldInput,
  FormActionInput,
  BuildFormRequest,
  BuildFormResponse,
  FormAction,
  ListFormActionsResponse,
  CreateLoopItemRequest,
  CreateLoopItemResponse,
  BindLoopGridRequest,
  BindLoopGridResponse,
  BindDynamicRequest,
  BindDynamicResponse,
  DynamicTagItem,
  ListDynamicTagsResponse,
  GetDynamicTagResponse,
  AddWooWidgetRequest,
  AddWooWidgetResponse,
  /* cache */
  CacheRegenRequest,
  CacheRegenResponse,
  CacheFlushRequest,
  CacheFlushResponse,
  /* ops */
  OpLogEntry,
  OpsLogRequest,
  OpsLogResponse,
  /* site */
  ExperimentState,
  SiteCapabilitiesResponse,
  /* batch */
  BatchStep,
  BatchPlanRequest,
  BatchPlanStepResult,
  BatchBackupRequirement,
  BatchPlanResponse,
  BatchApplyStep,
  BatchApplyRequest,
  BatchApplyStepResult,
  BatchApplyResponse,
} from './types.js';

/* Route registry (runtime + types). */
export {
  REST_NAMESPACE,
  REST_BASE_PATH,
  ROUTES,
  ROUTE_NAMES,
  ROUTE_COUNT,
  getRoute,
  buildRoutePath,
  type HttpMethod,
  type CapGate,
  type RouteDef,
  type RouteName,
} from './routes.js';
