/**
 * WP-F04 — the FROZEN MCP tool catalog as typed `ToolDescriptor[]` (Seam A, 13-tool-catalog.md §1).
 *
 * One descriptor per tool in Contract 13 §1.1-§1.11, with the EXACT frozen `name`, `title`,
 * `description`, `inputSchema` + `outputSchema` (ZodRawShape maps imported from `schemas/*`),
 * `annotations` (read/idempotent/destructive hints, §0.3), the lean ★ profile flag (§5.2), the safety
 * `class` (R/M/D, §0.4), the `side` (§0.5), the always-available meta flag (§5.2/§6), and the backing
 * REST `route` id from WP-F02's `ROUTES` registry where the tool 1:1 proxies a route (§1, impl note 8).
 *
 * This module contains NO handler logic — handlers are owned by the vertical tool WPs (WP-T##/H##/R##)
 * which `registry.attachHandler(name, fn)` by name (§Detailed Requirements 7). It freezes the surface
 * so `tools/list` returns the real names; the combined catalog rows
 * (`.globalColors.{list,upsert,delete}`, `.popup.set_triggers/.set_timing`, `.element_defaults.{get,
 * set}`, etc.) are ENUMERATED here as individual descriptors (impl note: "EXPAND to multiple named
 * tools").
 *
 * SDK shape (LOCKED, §0.1): `inputSchema`/`outputSchema` are ZodRawShape maps `{ field: zodType }`,
 * NEVER a top-level `z.object(...)` — the catalog tests guard this.
 */

import type { ZodRawShape } from 'zod';

import type { RouteName } from '@elementor-ultra/shared';

import * as discovery from './schemas/discovery.js';
import * as page from './schemas/page.js';
import * as widget from './schemas/widget.js';
import * as design from './schemas/design.js';
import * as media from './schemas/media.js';
import * as nav from './schemas/nav.js';
import * as templates from './schemas/templates.js';
import * as pro from './schemas/pro.js';
import * as convert from './schemas/convert.js';
import * as ops from './schemas/ops.js';
import * as meta from './schemas/meta.js';

/* ───────────────────────────── descriptor types ─────────────────────────────────────────── */

/** Safety class (13-tool-catalog.md §0.4). `R` read · `M` mutating-safe · `D` destructive. */
export type SafetyClass = 'R' | 'M' | 'D';

/** Side of implementation (13-tool-catalog.md §0.5). */
export type ToolSide = 'TS' | 'proxied-to-REST' | 'BOTH';

/** The three MCP annotation hints (13-tool-catalog.md §0.3). Unstated ⇒ false. */
export interface ToolAnnotations {
  readOnlyHint?: boolean;
  idempotentHint?: boolean;
  destructiveHint?: boolean;
}

/**
 * A single frozen tool descriptor. `inputSchema`/`outputSchema` are ZodRawShape maps (§0.1). `route`
 * is the WP-F02 `operationId` for 1:1-proxied tools (cross-checked by the tool↔route coverage test);
 * `undefined` for TS-only/orchestration tools that do not map to a single route. `meta:true` flags the
 * always-available meta-trio (§5.2/§6).
 */
export interface ToolDescriptor {
  name: string;
  title: string;
  description: string;
  inputSchema: ZodRawShape;
  outputSchema: ZodRawShape;
  annotations: ToolAnnotations;
  /** Lean ★ profile membership (§5.2). */
  star: boolean;
  /** Safety class (§0.4). */
  class: SafetyClass;
  /** Side of implementation (§0.5). */
  side: ToolSide;
  /** Backing REST route `operationId` (WP-F02 `ROUTES`) when the tool 1:1 proxies a route. */
  route?: RouteName;
  /** True for the always-available meta-trio (§5.2/§6). */
  meta?: boolean;
}

/** The frozen tool-name pattern (13-tool-catalog.md §0.2). */
export const TOOL_NAME_PATTERN = /^[A-Za-z0-9_.-]{1,128}$/;

/* ───────────────────────────── the catalog (§1.1 – §1.11) ───────────────────────────────── */

/**
 * EVERY tool in 13-tool-catalog.md §1, in catalog order. Frozen — adding/removing/renaming a tool is a
 * contract revision (the `catalog.snapshot.json` drift test fails otherwise).
 */
export const TOOL_DESCRIPTORS: readonly ToolDescriptor[] = [
  /* ─── §1.1 Discovery / read ─── */
  {
    name: 'elementor.tools.search',
    title: 'Search MCP tools',
    description:
      'Progressive discovery of the full Elementor tool surface; returns matching tool names + schemas so advanced tools can be enabled on demand.',
    inputSchema: discovery.toolsSearchInput,
    outputSchema: discovery.toolsSearchOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'TS',
  },
  {
    name: 'elementor.site.capabilities',
    title: 'Probe site capabilities',
    description:
      'Report experiments, Pro presence, registered element types, breakpoints, capabilities, and migration state for the target site.',
    inputSchema: discovery.siteCapabilitiesInput,
    outputSchema: discovery.siteCapabilitiesOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getSiteCapabilities',
  },
  {
    name: 'elementor.pages.list',
    title: 'List Elementor pages',
    description: 'List documents built with Elementor (paginated).',
    inputSchema: discovery.pagesListInput,
    outputSchema: discovery.pagesListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listDocuments',
  },
  {
    name: 'elementor.page.get_structure',
    title: 'Get page element tree',
    description:
      'Read the element tree of a document with depth / subtree / projection controls; returns the optimistic-lock base_hash.',
    inputSchema: discovery.pageGetStructureInput,
    outputSchema: discovery.pageGetStructureOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getDocument',
  },
  {
    name: 'elementor.page.get_settings',
    title: 'Get page settings',
    description: 'Read `_elementor_page_settings` for a document.',
    inputSchema: discovery.pageGetSettingsInput,
    outputSchema: discovery.pageGetSettingsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getDocumentSettings',
  },
  {
    name: 'elementor.schema.widget',
    title: 'Get widget schema',
    description:
      'Per-widget props schema for an atomic widget (post-filter `get_props_schema()`, includes `_cssid` + dynamic-capable flags) or classic widget controls.',
    inputSchema: discovery.schemaWidgetInput,
    outputSchema: discovery.schemaWidgetOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'schemaWidget',
  },
  {
    name: 'elementor.schema.styles',
    title: 'Get atomic Style-Schema',
    description: 'The flat atomic Style-Schema (css-prop → prop-type), unit presets, and enums.',
    inputSchema: discovery.schemaStylesInput,
    outputSchema: discovery.schemaStylesOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'schemaStyles',
  },
  {
    name: 'elementor.breakpoints.get',
    title: 'Get active breakpoints',
    description: 'Active Elementor breakpoints with direction (min/max) and width.',
    inputSchema: discovery.breakpointsGetInput,
    outputSchema: discovery.breakpointsGetOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'schemaBreakpoints',
  },
  {
    name: 'elementor.dynamic.list_tags',
    title: 'List dynamic tags',
    description: 'Available dynamic tags on the site, by category.',
    inputSchema: discovery.dynamicListTagsInput,
    outputSchema: discovery.dynamicListTagsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listDynamicTags',
  },
  {
    name: 'elementor.dynamic.get_tag_schema',
    title: 'Get dynamic tag schema',
    description: 'Per-tag controls/args and categories for binding.',
    inputSchema: discovery.dynamicGetTagSchemaInput,
    outputSchema: discovery.dynamicGetTagSchemaOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getDynamicTag',
  },

  /* ─── §1.2 Page CRUD ─── */
  {
    name: 'elementor.page.create',
    title: 'Create blank page',
    description: 'Create a blank Elementor document.',
    inputSchema: page.pageCreateInput,
    outputSchema: page.pageCreateOutput,
    annotations: {},
    star: true,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createDocument',
  },
  {
    name: 'elementor.page.build',
    title: 'Build page from tree',
    description:
      'Batch create-and-populate a document from a declarative element tree; validates via PHP dry_run, saves, and primes atomic CSS.',
    inputSchema: page.pageBuildInput,
    outputSchema: page.pageBuildOutput,
    annotations: { idempotentHint: true },
    star: true,
    class: 'M',
    side: 'BOTH',
  },
  {
    name: 'elementor.page.replace_tree',
    title: 'Replace page tree',
    description:
      'Overwrite the entire element tree of a document in one transaction (optimistic-lock guarded).',
    inputSchema: page.pageReplaceTreeInput,
    outputSchema: page.pageReplaceTreeOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'saveDocument',
  },
  {
    name: 'elementor.page.update_settings',
    title: 'Update page settings',
    description:
      'Patch document / page settings (GET-merge-PUT so partial updates never wipe unrelated keys).',
    inputSchema: page.pageUpdateSettingsInput,
    outputSchema: page.pageUpdateSettingsOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'updateDocumentSettings',
  },
  {
    name: 'elementor.page.dry_run',
    title: 'Dry-run validate page',
    description:
      'Authoritative validate-and-diff of an element tree with NO persistence (PHP instantiates every node + get_data_for_save).',
    inputSchema: page.pageDryRunInput,
    outputSchema: page.pageDryRunOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'dryRunDocument',
  },
  {
    name: 'elementor.page.duplicate',
    title: 'Duplicate page',
    description: 'Deep-copy a document and its meta (ids regenerated).',
    inputSchema: page.pageDuplicateInput,
    outputSchema: page.pageDuplicateOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'duplicateDocument',
  },
  {
    name: 'elementor.page.delete',
    title: 'Delete page',
    description: 'Trash a document.',
    inputSchema: page.pageDeleteInput,
    outputSchema: page.pageDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'deleteDocument',
  },
  {
    name: 'elementor.page.export_template',
    title: 'Export page as template',
    description:
      'Emit a document in library-format JSON (content + page settings + bundled global classes/variables).',
    inputSchema: page.pageExportTemplateInput,
    outputSchema: page.pageExportTemplateOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'exportDocument',
  },
  {
    name: 'elementor.page.list_backups',
    title: 'List page backups',
    description:
      'List the pre-write backup snapshots for a document (paginated); each carries the meta_key + base_hash to roll back to.',
    inputSchema: page.pageListBackupsInput,
    outputSchema: page.pageListBackupsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listBackups',
  },
  {
    name: 'elementor.page.rollback',
    title: 'Roll back page',
    description:
      'Restore a document to a prior backup snapshot (by meta_key or "latest"), then re-prime atomic CSS.',
    inputSchema: page.pageRollbackInput,
    outputSchema: page.pageRollbackOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'rollbackDocument',
  },
  {
    name: 'elementor.page.verify_render',
    title: 'Verify page renders',
    description:
      'Probe that a document actually RENDERS (permalink loopback with in-process front-controller dispatch fallback): asserts HTTP 200 + no fatal marker; a fatal returns render_verified:false (RENDER_FAILED, op-logged).',
    inputSchema: page.pageVerifyRenderInput,
    outputSchema: page.pageVerifyRenderOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'verifyRenderDocument',
  },

  /* ─── §1.3 Widget / element ops ─── */
  {
    name: 'elementor.element.get',
    title: 'Get element',
    description: 'Read a single node from a document tree.',
    inputSchema: widget.elementGetInput,
    outputSchema: widget.elementGetOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getDocument',
  },
  {
    name: 'elementor.widget.insert',
    title: 'Insert widget',
    description:
      'Insert a node under a parent at an index (transactional, optimistic-lock + idempotency guarded).',
    inputSchema: widget.widgetInsertInput,
    outputSchema: widget.widgetInsertOutput,
    annotations: { idempotentHint: true },
    star: true,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.widget.update_settings',
    title: 'Update widget settings',
    description: "Patch a single node's settings (transactional).",
    inputSchema: widget.widgetUpdateSettingsInput,
    outputSchema: widget.widgetUpdateSettingsOutput,
    annotations: { idempotentHint: true },
    star: true,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.move',
    title: 'Move element',
    description: 'Reorder or reparent a node.',
    inputSchema: widget.elementMoveInput,
    outputSchema: widget.elementMoveOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.delete',
    title: 'Delete element',
    description: 'Remove a node and its subtree.',
    inputSchema: widget.elementDeleteInput,
    outputSchema: widget.elementDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.set_classes',
    title: 'Set element classes',
    description: 'Set the `classes` prop (global + local class ids) on a node.',
    inputSchema: widget.elementSetClassesInput,
    outputSchema: widget.elementSetClassesOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.set_local_style',
    title: 'Upsert local style',
    description:
      "Upsert a local style variant on a node (mirrors the style id into the element's classes prop).",
    inputSchema: widget.elementSetLocalStyleInput,
    outputSchema: widget.elementSetLocalStyleOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.bind_dynamic',
    title: 'Bind dynamic value',
    description: 'Bind a dynamic tag to a control (V3 `__dynamic__` or V4 atomic dynamic prop).',
    inputSchema: widget.elementBindDynamicInput,
    outputSchema: widget.elementBindDynamicOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },
  {
    name: 'elementor.element.bind_global',
    title: 'Bind global value',
    description: 'Bind a V3 global color/typography to a control via `__globals__`.',
    inputSchema: widget.elementBindGlobalInput,
    outputSchema: widget.elementBindGlobalOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'elementOps',
  },

  /* ─── §1.4 Design-system ops ─── */
  {
    name: 'elementor.design.classes.list',
    title: 'List global classes',
    description: 'Global classes with variants + order (paginated).',
    inputSchema: design.designClassesListInput,
    outputSchema: design.designClassesListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listGlobalClasses',
  },
  {
    name: 'elementor.design.classes.upsert',
    title: 'Upsert global classes',
    description:
      'Add or modify global classes via a diff-PUT (PHP builds the changes/items/order body; budget + duplicate-label aware).',
    inputSchema: design.designClassesUpsertInput,
    outputSchema: design.designClassesUpsertOutput,
    annotations: { idempotentHint: true },
    star: true,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'putGlobalClasses',
  },
  {
    name: 'elementor.design.classes.delete',
    title: 'Delete global classes',
    description: 'Remove global classes by id (explicit deletion).',
    inputSchema: design.designClassesDeleteInput,
    outputSchema: design.designClassesDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'putGlobalClasses',
  },
  {
    name: 'elementor.design.classes.reorder',
    title: 'Reorder global classes',
    description: 'Set the full ordering of global classes.',
    inputSchema: design.designClassesReorderInput,
    outputSchema: design.designClassesReorderOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'putGlobalClasses',
  },
  {
    name: 'elementor.design.classes.usage',
    title: 'Global class usage',
    description: 'Where each global class is used.',
    inputSchema: design.designClassesUsageInput,
    outputSchema: design.designClassesUsageOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'globalClassesUsage',
  },
  {
    name: 'elementor.design.variables.list',
    title: 'List design variables',
    description: 'Design tokens (color/font/size) + optimistic watermark.',
    inputSchema: design.designVariablesListInput,
    outputSchema: design.designVariablesListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: true,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listVariables',
  },
  {
    name: 'elementor.design.variables.create',
    title: 'Create design variable',
    description: 'Create a color/font/size token (all three are FREE in 4.1.x).',
    inputSchema: design.designVariablesCreateInput,
    outputSchema: design.designVariablesCreateOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createVariable',
  },
  {
    name: 'elementor.design.variables.update',
    title: 'Update design variable',
    description: 'Edit a token (watermark-guarded).',
    inputSchema: design.designVariablesUpdateInput,
    outputSchema: design.designVariablesUpdateOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'updateVariable',
  },
  {
    name: 'elementor.design.variables.delete',
    title: 'Delete design variable',
    description: 'Soft-delete a token (watermark-guarded).',
    inputSchema: design.designVariablesDeleteInput,
    outputSchema: design.designVariablesDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'deleteVariable',
  },
  {
    name: 'elementor.design.variables.restore',
    title: 'Restore design variable',
    description: 'Restore a soft-deleted token (watermark-guarded).',
    inputSchema: design.designVariablesRestoreInput,
    outputSchema: design.designVariablesRestoreOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'restoreVariable',
  },
  {
    name: 'elementor.design.variables.batch',
    title: 'Batch edit variables',
    description: 'Atomic multi-edit of tokens (single watermark).',
    inputSchema: design.designVariablesBatchInput,
    outputSchema: design.designVariablesBatchOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'batchVariables',
  },
  {
    name: 'elementor.design.globalColors.list',
    title: 'V3 global colors list',
    description: 'Read/write V3 kit color repeaters (`system_colors`/`custom_colors`).',
    inputSchema: design.designGlobalColorsListInput,
    outputSchema: design.designGlobalColorsListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getGlobalColors',
  },
  {
    name: 'elementor.design.globalColors.upsert',
    title: 'V3 global colors upsert',
    description: 'Read/write V3 kit color repeaters (`system_colors`/`custom_colors`).',
    inputSchema: design.designGlobalColorsUpsertInput,
    outputSchema: design.designGlobalColorsUpsertOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'putGlobalColors',
  },
  {
    name: 'elementor.design.globalColors.delete',
    title: 'V3 global colors delete',
    description: 'Read/write V3 kit color repeaters (`system_colors`/`custom_colors`).',
    inputSchema: design.designGlobalColorsDeleteInput,
    outputSchema: design.designGlobalColorsDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'putGlobalColors',
  },
  {
    name: 'elementor.design.globalFonts.list',
    title: 'V3 global fonts list',
    description:
      'Read/write V3 kit typography repeaters (`system_typography`/`custom_typography`).',
    inputSchema: design.designGlobalFontsListInput,
    outputSchema: design.designGlobalFontsListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getGlobalFonts',
  },
  {
    name: 'elementor.design.globalFonts.upsert',
    title: 'V3 global fonts upsert',
    description:
      'Read/write V3 kit typography repeaters (`system_typography`/`custom_typography`).',
    inputSchema: design.designGlobalFontsUpsertInput,
    outputSchema: design.designGlobalFontsUpsertOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'putGlobalFonts',
  },
  {
    name: 'elementor.design.globalFonts.delete',
    title: 'V3 global fonts delete',
    description:
      'Read/write V3 kit typography repeaters (`system_typography`/`custom_typography`).',
    inputSchema: design.designGlobalFontsDeleteInput,
    outputSchema: design.designGlobalFontsDeleteOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'putGlobalFonts',
  },
  {
    name: 'elementor.design.fonts.install',
    title: 'Install font face',
    description:
      'Install a NON-Google-catalog font face (contract 18 §7-AI S4): store woff2/woff/ttf/otf bytes under uploads, register its @font-face (Pro Custom Fonts CPT when available, else kit custom CSS), and return the resolved family string for atomic font-family props.',
    inputSchema: design.designFontsInstallInput,
    outputSchema: design.designFontsInstallOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'installFont',
  },
  {
    name: 'elementor.design.fonts.upload_zip',
    title: 'Upload font ZIP to WP Font Library',
    description:
      "Extract a ZIP of font files (OTF/TTF/WOFF/WOFF2) and install every face into the WP Font Library. Reads font family names and weights automatically from each file's OTF/TTF name table — no manual metadata needed. Accepts file_path (local path to ZIP on the server filesystem) or zip_data (base64-encoded ZIP). Returns the list of installed faces and any skipped files.",
    inputSchema: design.designFontsUploadZipInput,
    outputSchema: design.designFontsUploadZipOutput,
    annotations: { idempotentHint: false },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'uploadFontZip',
  },
  {
    name: 'elementor.design.sync_v4_to_v3',
    title: 'Sync V4 variable to V3',
    description: 'Flag a V4 variable `sync_to_v3` and regenerate the bridge stylesheet.',
    inputSchema: design.designSyncV4ToV3Input,
    outputSchema: design.designSyncV4ToV3Output,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'syncV4ToV3',
  },
  {
    name: 'elementor.design.element_defaults.get',
    title: 'Element defaults get',
    description: 'Per-widget kit default settings.',
    inputSchema: design.designElementDefaultsGetInput,
    outputSchema: design.designElementDefaultsGetOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getElementDefaults',
  },
  {
    name: 'elementor.design.element_defaults.set',
    title: 'Element defaults set',
    description: 'Per-widget kit default settings.',
    inputSchema: design.designElementDefaultsSetInput,
    outputSchema: design.designElementDefaultsSetOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'putElementDefaults',
  },
  {
    name: 'elementor.design.deploy',
    title: 'Deploy design system',
    description:
      'Bulk-deploy global classes + variables in one transaction (budget pre-flighted, full cache flush after).',
    inputSchema: design.designDeployInput,
    outputSchema: design.designDeployOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'BOTH',
  },

  /* ─── §1.5 Media / library ─── */
  {
    name: 'elementor.media.sideload_url',
    title: 'Sideload image from URL',
    description: 'Import an external image into the WP media library (deduped by source hash).',
    inputSchema: media.mediaSideloadUrlInput,
    outputSchema: media.mediaSideloadUrlOutput,
    annotations: { idempotentHint: true },
    star: true,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'sideloadMedia',
  },
  {
    name: 'elementor.media.upload',
    title: 'Upload media',
    description: 'Upload raw bytes/base64 to the media library.',
    inputSchema: media.mediaUploadInput,
    outputSchema: media.mediaUploadOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'uploadMedia',
  },
  {
    name: 'elementor.media.list',
    title: 'List media',
    description: 'Search/list attachments.',
    inputSchema: media.mediaListInput,
    outputSchema: media.mediaListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listMedia',
  },

  /* ─── §1.6 Navigation / menus ─── */
  {
    name: 'elementor.nav.menus.list',
    title: 'List nav menus',
    description: 'List WP navigation menus.',
    inputSchema: nav.navMenusListInput,
    outputSchema: nav.navMenusListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listNavMenus',
  },
  {
    name: 'elementor.nav.menus.create',
    title: 'Create nav menu',
    description: 'Create and populate a navigation menu.',
    inputSchema: nav.navMenusCreateInput,
    outputSchema: nav.navMenusCreateOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createNavMenu',
  },
  {
    name: 'elementor.nav.bind_widget',
    title: 'Bind nav widget to menu',
    description: 'Bind a Pro nav-menu/mega-menu widget to a menu term.',
    inputSchema: nav.navBindWidgetInput,
    outputSchema: nav.navBindWidgetOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'bindNavWidget',
  },

  /* ─── §1.7 Templates / kits ─── */
  {
    name: 'elementor.templates.list',
    title: 'List templates',
    description: 'Template library list (paginated).',
    inputSchema: templates.templatesListInput,
    outputSchema: templates.templatesListOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listTemplates',
  },
  {
    name: 'elementor.templates.get',
    title: 'Get template',
    description: 'Template content + settings.',
    inputSchema: templates.templatesGetInput,
    outputSchema: templates.templatesGetOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getTemplate',
  },
  {
    name: 'elementor.templates.save',
    title: 'Save template',
    description:
      'Persist a reusable block/page template (ids regenerated by Source_Local::save_item).',
    inputSchema: templates.templatesSaveInput,
    outputSchema: templates.templatesSaveOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'saveTemplate',
  },
  {
    name: 'elementor.templates.import',
    title: 'Import template',
    description: 'Import a .json/.zip template (image sideload + id remap).',
    inputSchema: templates.templatesImportInput,
    outputSchema: templates.templatesImportOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'importTemplate',
  },
  {
    name: 'elementor.templates.insert_into_page',
    title: 'Insert template into page',
    description: 'Paste a block into a document (ids minted fresh).',
    inputSchema: templates.templatesInsertIntoPageInput,
    outputSchema: templates.templatesInsertIntoPageOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'insertTemplate',
  },
  {
    name: 'elementor.kit.export',
    title: 'Export kit',
    description: 'Full-site kit export zip.',
    inputSchema: templates.kitExportInput,
    outputSchema: templates.kitExportOutput,
    annotations: { readOnlyHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'kitExport',
  },
  {
    name: 'elementor.kit.import',
    title: 'Import kit',
    description: 'Upload + import a kit zip.',
    inputSchema: templates.kitImportInput,
    outputSchema: templates.kitImportOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'kitImport',
  },
  {
    name: 'elementor.kit.revert',
    title: 'Revert kit import',
    description: 'Revert a kit import session.',
    inputSchema: templates.kitRevertInput,
    outputSchema: templates.kitRevertOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'D',
    side: 'proxied-to-REST',
    route: 'kitRevert',
  },

  /* ─── §1.8 Pro surface ─── */
  {
    name: 'elementor.pro.theme.create',
    title: 'Create theme-builder doc',
    description:
      'Create a header/footer/single/archive/404/search/section theme-builder document with conditions.',
    inputSchema: pro.proThemeCreateInput,
    outputSchema: pro.proThemeCreateOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createThemeDoc',
  },
  {
    name: 'elementor.pro.theme.set_conditions',
    title: 'Set display conditions',
    description:
      'Replace all display conditions on a theme doc (via Conditions_Manager::save_conditions + cache regenerate).',
    inputSchema: pro.proThemeSetConditionsInput,
    outputSchema: pro.proThemeSetConditionsOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'setThemeConditions',
  },
  {
    name: 'elementor.pro.theme.get_conditions_config',
    title: 'Get conditions config',
    description: 'Valid condition keys / sub-conditions per location (autocomplete tree).',
    inputSchema: pro.proThemeGetConditionsConfigInput,
    outputSchema: pro.proThemeGetConditionsConfigOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'getConditionsConfig',
  },
  {
    name: 'elementor.pro.popup.create',
    title: 'Create popup',
    description:
      'Create a popup document with layout settings, display settings (triggers/timing), and conditions.',
    inputSchema: pro.proPopupCreateInput,
    outputSchema: pro.proPopupCreateOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createPopup',
  },
  {
    name: 'elementor.pro.popup.set_triggers',
    title: 'Set popup triggers',
    description: 'Merge into the existing `_elementor_popup_display_settings`.',
    inputSchema: pro.proPopupSetTriggersInput,
    outputSchema: pro.proPopupSetTriggersOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'setPopupDisplay',
  },
  {
    name: 'elementor.pro.popup.set_timing',
    title: 'Set popup timing',
    description: 'Merge into the existing `_elementor_popup_display_settings`.',
    inputSchema: pro.proPopupSetTimingInput,
    outputSchema: pro.proPopupSetTimingOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'setPopupDisplay',
  },
  {
    name: 'elementor.pro.form.build',
    title: 'Build form widget',
    description:
      'Build an Elementor form widget (V3 classic `form`, or atomic `e-form` when `e_pro_atomic_form` active) with fields + actions.',
    inputSchema: pro.proFormBuildInput,
    outputSchema: pro.proFormBuildOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'BOTH',
    route: 'buildForm',
  },
  {
    name: 'elementor.pro.form.list_actions',
    title: 'List form actions',
    description: 'Registered (license-gated) form actions and their settings controls.',
    inputSchema: pro.proFormListActionsInput,
    outputSchema: pro.proFormListActionsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listFormActions',
  },
  {
    name: 'elementor.pro.loop.create_item',
    title: 'Create loop item',
    description: 'Create a loop-item template document.',
    inputSchema: pro.proLoopCreateItemInput,
    outputSchema: pro.proLoopCreateItemOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'proxied-to-REST',
    route: 'createLoopItem',
  },
  {
    name: 'elementor.pro.loop.bind_grid',
    title: 'Bind loop grid',
    description: 'Configure a loop-grid/carousel widget bound to a loop-item template + query.',
    inputSchema: pro.proLoopBindGridInput,
    outputSchema: pro.proLoopBindGridOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'BOTH',
    route: 'bindLoopGrid',
  },
  {
    name: 'elementor.pro.dynamic.bind',
    title: 'Bind dynamic tag (Pro)',
    description: 'Byte-identical mirror of core Manager::tag_to_text for dynamic binding.',
    inputSchema: pro.proDynamicBindInput,
    outputSchema: pro.proDynamicBindOutput,
    annotations: { idempotentHint: true },
    star: false,
    class: 'M',
    side: 'BOTH',
    route: 'bindDynamic',
  },
  {
    name: 'elementor.pro.dynamic.list_tags',
    title: 'List dynamic tags (Pro)',
    description: 'Per-tag name/title/group/categories/settings controls/availability.',
    inputSchema: pro.proDynamicListTagsInput,
    outputSchema: pro.proDynamicListTagsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'listDynamicTags',
  },
  {
    name: 'elementor.pro.woo.add_widget',
    title: 'Add WooCommerce widget',
    description: 'Add a context-validated WooCommerce widget (single/archive/context-free).',
    inputSchema: pro.proWooAddWidgetInput,
    outputSchema: pro.proWooAddWidgetOutput,
    annotations: {},
    star: false,
    class: 'M',
    side: 'BOTH',
    route: 'addWooWidget',
  },

  /* ─── §1.9 HTML → native conversion ─── */
  {
    name: 'elementor.convert.html_to_tree',
    title: 'Convert HTML to element tree',
    description:
      'Convert HTML+CSS into a native atomic element tree with proposed classes/variables and a coverage report (NO persistence).',
    inputSchema: convert.convertHtmlToTreeInput,
    outputSchema: convert.convertHtmlToTreeOutput,
    annotations: { readOnlyHint: true },
    star: true,
    class: 'R',
    side: 'TS',
  },
  {
    name: 'elementor.convert.html_to_page',
    title: 'Convert HTML to page',
    description:
      'Convert HTML, sideload media, create classes/variables, validate, and (only on explicit commit) create/replace the page + prime CSS. NEVER auto-commits.',
    inputSchema: convert.convertHtmlToPageInput,
    outputSchema: convert.convertHtmlToPageOutput,
    annotations: { destructiveHint: true },
    star: true,
    class: 'M',
    side: 'BOTH',
  },
  {
    name: 'elementor.convert.fidelity_check',
    title: 'Fidelity check',
    description: 'Render the saved page and visual-compare against the source HTML (pixelmatch).',
    inputSchema: convert.convertFidelityCheckInput,
    outputSchema: convert.convertFidelityCheckOutput,
    annotations: { readOnlyHint: true },
    star: false,
    class: 'R',
    side: 'BOTH',
  },

  /* ─── contract 18 §6 Figma → native conversion (full profile only — non-★) ─── */
  {
    name: 'elementor.convert.figma_to_tree',
    title: 'Convert Figma frame to element tree',
    description:
      'Fetch a Figma frame (fetch-to-file with manifest resume) and convert it into a native atomic element tree with proposed classes/variables, a coverage report, and the figma frame/tokens/flatten record (NO page persistence).',
    inputSchema: convert.convertFigmaToTreeInput,
    outputSchema: convert.convertFigmaToTreeOutput,
    annotations: { readOnlyHint: true },
    star: false,
    class: 'R',
    side: 'TS',
  },
  {
    name: 'elementor.convert.figma_to_page',
    title: 'Convert Figma frame to page',
    description:
      'Convert a Figma frame, sideload its assets (attachment ids only — temp asset URLs never persist), validate, and (only on explicit commit) create/replace the page + prime CSS + verify against the Figma frame render. NEVER auto-commits.',
    inputSchema: convert.convertFigmaToPageInput,
    outputSchema: convert.convertFigmaToPageOutput,
    annotations: { destructiveHint: true },
    star: false,
    class: 'M',
    side: 'BOTH',
  },

  /* ─── §1.10 Ops / observability ─── */
  {
    name: 'elementor.ops.log',
    title: 'Operation audit log',
    description: 'Audit trail of writes (op_id, before/after hashes, result).',
    inputSchema: ops.opsLogInput,
    outputSchema: ops.opsLogOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'proxied-to-REST',
    route: 'opsLog',
  },
  {
    name: 'elementor.batch.plan',
    title: 'Plan multi-doc build',
    description: 'Dry-plan a multi-document brief build (records required backups).',
    inputSchema: ops.batchPlanInput,
    outputSchema: ops.batchPlanOutput,
    annotations: { readOnlyHint: true },
    star: false,
    class: 'R',
    side: 'BOTH',
  },
  {
    name: 'elementor.batch.apply',
    title: 'Apply multi-doc plan',
    description:
      'Execute a multi-document plan with up-front backups and best-effort compensation on partial failure.',
    inputSchema: ops.batchApplyInput,
    outputSchema: ops.batchApplyOutput,
    annotations: { destructiveHint: true, idempotentHint: true },
    star: false,
    class: 'D',
    side: 'BOTH',
  },

  /* ─── §1.11 Meta-tool trio (always available, §5.2/§6) ─── */
  {
    name: 'elementor.tools.list_endpoints',
    title: 'List tool endpoints',
    description: 'Enumerate every tool (incl. disabled) with namespace + safety class.',
    inputSchema: meta.toolsListEndpointsInput,
    outputSchema: meta.toolsListEndpointsOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'TS',
    meta: true,
  },
  {
    name: 'elementor.tools.get_schema',
    title: 'Get tool schema',
    description: 'Return the input/output schema + annotations for a named tool.',
    inputSchema: meta.toolsGetSchemaInput,
    outputSchema: meta.toolsGetSchemaOutput,
    annotations: { readOnlyHint: true, idempotentHint: true },
    star: false,
    class: 'R',
    side: 'TS',
    meta: true,
  },
  {
    name: 'elementor.tools.invoke',
    title: 'Invoke tool by name',
    description:
      "Invoke any catalog tool (incl. disabled) by name with a payload; mirrors the named tool's safety class + confirm gating.",
    inputSchema: meta.toolsInvokeInput,
    outputSchema: meta.toolsInvokeOutput,
    annotations: {},
    star: false,
    // Class inherits the target at call time; the descriptor records the dispatch tool's own class.
    class: 'R',
    side: 'TS',
    meta: true,
  },
] as const;

/** Frozen list of all tool names in catalog order. */
export const TOOL_NAMES: readonly string[] = TOOL_DESCRIPTORS.map((t) => t.name);

/** Total tool count in the frozen catalog. */
export const TOOL_COUNT: number = TOOL_DESCRIPTORS.length;
